["ru-ru"]
  languageName = "Русский"
  languageCode = "ru-ru"
  weight = 1
  title = "Linux | Network | DevOps"
  
  ["ru-ru".params]
    tagline = "Авторский сайт для тех кто изучает Linux, Network, DevOps, NetDevOps, DevNet, Bash, Git, CI/CD, Docker, Kubernetes, Ansible, Terraform, Prometheus, Grafana, Zabbix"
